# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mpesa.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("mpesa.proto", :syntax => :proto3) do
    add_message "kash.services.AuthorizationSuccessResponse" do
      optional :expiry_in, :string, 1
      optional :access_token, :string, 2
    end
    add_message "kash.services.AuthorizationErrorResponse" do
      optional :request_id, :string, 1
      optional :error_code, :string, 2
      optional :error_message, :string, 3
    end
    add_message "kash.services.AuthorizationExceptionResponse" do
      optional :exception_code, :string, 1
      optional :exception_message, :string, 2
    end
    add_message "kash.services.AuthorizationRequest" do
      optional :consumer_key, :string, 1
      optional :consumer_secret, :string, 2
      optional :grant_type, :string, 3
    end
    add_message "kash.services.AuthorizationResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :success, :message, 2, "kash.services.AuthorizationSuccessResponse"
        optional :error, :message, 3, "kash.services.AuthorizationErrorResponse"
        optional :exception, :message, 4, "kash.services.AuthorizationExceptionResponse"
      end
    end
    add_message "kash.services.DynamicQRCodeSuccessResponse" do
      optional :response_code, :string, 1
      optional :response_description, :string, 2
      optional :qr_code, :string, 3
    end
    add_message "kash.services.DynamicQRCodeErrorResponse" do
      optional :request_id, :string, 1
      optional :error_code, :string, 2
      optional :error_message, :string, 3
    end
    add_message "kash.services.DynamicQRCodeExceptionResponse" do
      optional :exception_code, :string, 1
      optional :exception_message, :string, 2
    end
    add_message "kash.services.DynamicQRCodeRequest" do
      optional :qr_version, :string, 1
      optional :trx_code, :string, 2
      optional :cpi, :string, 3
      optional :merchant_name, :string, 4
      optional :amount, :string, 5
      optional :ref_no, :string, 6
      optional :qr_format, :int32, 7
      optional :qr_type, :string, 8
    end
    add_message "kash.services.DynamicQRCodeResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :success, :message, 2, "kash.services.DynamicQRCodeSuccessResponse"
        optional :error, :message, 3, "kash.services.DynamicQRCodeErrorResponse"
        optional :exception, :message, 4, "kash.services.DynamicQRCodeExceptionResponse"
      end
    end
    add_message "kash.services.StkPushSuccessResponse" do
      optional :merchant_request_id, :string, 1
      optional :checkout_request_id, :string, 2
      optional :response_description, :string, 3
      optional :response_code, :string, 4
      optional :customer_message, :string, 5
    end
    add_message "kash.services.StkPushErrorResponse" do
      optional :request_id, :string, 1
      optional :error_code, :string, 2
      optional :error_message, :string, 3
    end
    add_message "kash.services.StkPushExceptionResponse" do
      optional :exception_code, :string, 1
      optional :exception_message, :string, 2
    end
    add_message "kash.services.StkPushRequest" do
      optional :business_short_code, :int32, 1
      optional :password, :string, 2
      optional :timestamp, :message, 3, "google.protobuf.Timestamp"
      optional :transaction_type, :string, 4
      optional :amount, :int32, 5
      optional :party_a, :int32, 6
      optional :party_b, :int32, 7
      optional :phone_number, :int32, 8
      optional :call_back_url, :string, 9
      optional :account_reference, :string, 10
      optional :transaction_desc, :string, 11
    end
    add_message "kash.services.StkPushResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :success, :message, 2, "kash.services.StkPushSuccessResponse"
        optional :error, :message, 3, "kash.services.StkPushErrorResponse"
        optional :exception, :message, 4, "kash.services.StkPushExceptionResponse"
      end
    end
    add_message "kash.services.Callback" do
      optional :merchant_request_id, :string, 1
      optional :checkout_request_id, :string, 2
      optional :result_desc, :string, 3
      optional :result_code, :string, 4
    end
    add_message "kash.services.Dataset" do
      optional :name, :string, 1
      optional :value, :string, 2
    end
    add_message "kash.services.Metadata" do
      repeated :dataset_array, :message, 1, "kash.services.Dataset"
    end
    add_message "kash.services.StkPushCallbackSuccessResponse" do
      optional :callback, :message, 1, "kash.services.Callback"
      optional :metadata, :message, 2, "kash.services.Metadata"
    end
    add_message "kash.services.StkPushCallbackErrorResponse" do
      optional :request_id, :string, 1
      optional :error_code, :string, 2
      optional :error_message, :string, 3
    end
    add_message "kash.services.StkPushCallbackExceptionResponse" do
      optional :exception_code, :string, 1
      optional :exception_message, :string, 2
    end
    add_message "kash.services.StkPushCallbackRequest" do
      optional :callback, :message, 1, "kash.services.Callback"
      optional :metadata, :message, 2, "kash.services.Metadata"
    end
    add_message "kash.services.StkPushCallbackResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :success, :message, 2, "kash.services.StkPushCallbackSuccessResponse"
        optional :error, :message, 3, "kash.services.StkPushCallbackErrorResponse"
        optional :exception, :message, 4, "kash.services.StkPushCallbackExceptionResponse"
      end
    end
    add_message "kash.services.StkPushQuerySuccessResponse" do
      optional :merchant_request_id, :string, 1
      optional :checkout_request_id, :string, 2
      optional :response_code, :string, 3
      optional :result_desc, :string, 4
      optional :response_description, :string, 5
      optional :result_code, :string, 6
    end
    add_message "kash.services.StkPushQueryErrorResponse" do
      optional :request_id, :string, 1
      optional :error_code, :string, 2
      optional :error_message, :string, 3
    end
    add_message "kash.services.StkPushQueryExceptionResponse" do
      optional :exception_code, :string, 1
      optional :exception_message, :string, 2
    end
    add_message "kash.services.StkPushQueryRequest" do
      optional :business_short_code, :int32, 1
      optional :password, :string, 2
      optional :timestamp, :message, 3, "google.protobuf.Timestamp"
      optional :checkout_request_id, :string, 4
    end
    add_message "kash.services.StkPushQueryResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :success, :message, 2, "kash.services.StkPushQuerySuccessResponse"
        optional :error, :message, 3, "kash.services.StkPushQueryErrorResponse"
        optional :exception, :message, 4, "kash.services.StkPushQueryExceptionResponse"
      end
    end
    add_message "kash.services.CustomerToBusinessRegisterUrlSuccessResponse" do
      optional :originator_conversation_id, :string, 1
      optional :conversation_id, :string, 2
      optional :response_description, :string, 3
    end
    add_message "kash.services.CustomerToBusinessRegisterUrlErrorResponse" do
      optional :request_id, :string, 1
      optional :error_code, :string, 2
      optional :error_message, :string, 3
    end
    add_message "kash.services.CustomerToBusinessRegisterUrlExceptionResponse" do
      optional :exception_code, :string, 1
      optional :exception_message, :string, 2
    end
    add_message "kash.services.CustomerToBusinessRegisterUrlRequest" do
      optional :validation_url, :string, 1
      optional :confirmation_url, :string, 2
      optional :response_type, :string, 3
      optional :short_code, :int32, 4
    end
    add_message "kash.services.CustomerToBusinessRegisterUrlResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :success, :message, 2, "kash.services.CustomerToBusinessRegisterUrlSuccessResponse"
        optional :error, :message, 3, "kash.services.CustomerToBusinessRegisterUrlErrorResponse"
        optional :exception, :message, 4, "kash.services.CustomerToBusinessRegisterUrlExceptionResponse"
      end
    end
    add_message "kash.services.CustomerToBusinessPaymentSuccessResponse" do
      optional :originator_conversation_id, :string, 1
      optional :conversation_id, :string, 2
      optional :response_description, :string, 3
    end
    add_message "kash.services.CustomerToBusinessPaymentErrorResponse" do
      optional :request_id, :string, 1
      optional :error_code, :string, 2
      optional :error_message, :string, 3
    end
    add_message "kash.services.CustomerToBusinessPaymentExceptionResponse" do
      optional :exception_code, :string, 1
      optional :exception_message, :string, 2
    end
    add_message "kash.services.CustomerToBusinessPaymentRequest" do
      optional :command_id, :string, 1
      optional :amount, :int32, 2
      optional :msisdn, :int32, 3
      optional :bill_ref_number, :string, 4
      optional :short_code, :int32, 5
    end
    add_message "kash.services.CustomerToBusinessPaymentResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :success, :message, 2, "kash.services.CustomerToBusinessPaymentSuccessResponse"
        optional :error, :message, 3, "kash.services.CustomerToBusinessPaymentErrorResponse"
        optional :exception, :message, 4, "kash.services.CustomerToBusinessPaymentExceptionResponse"
      end
    end
    add_message "kash.services.CustomerToBusinessPaymentResultSuccessResponse" do
      optional :transaction_type, :string, 1
      optional :trans_id, :string, 2
      optional :trans_time, :message, 3, "google.protobuf.Timestamp"
      optional :trans_amount, :int32, 4
      optional :business_short_code, :string, 5
      optional :bill_ref_number, :string, 6
      optional :org_account_balance, :int32, 7
      optional :third_party_trans_id, :string, 8
      optional :msisdn, :string, 9
      optional :first_name, :string, 10
      optional :middle_name, :string, 11
      optional :last_name, :string, 12
    end
    add_message "kash.services.CustomerToBusinessPaymentResultErrorResponse" do
      optional :request_id, :string, 1
      optional :error_code, :string, 2
      optional :error_message, :string, 3
    end
    add_message "kash.services.CustomerToBusinessPaymentResultExceptionResponse" do
      optional :exception_code, :string, 1
      optional :exception_message, :string, 2
    end
    add_message "kash.services.CustomerToBusinessPaymentResultRequest" do
      optional :transaction_type, :string, 1
      optional :trans_id, :string, 2
      optional :trans_time, :message, 3, "google.protobuf.Timestamp"
      optional :trans_amount, :int32, 4
      optional :business_short_code, :string, 5
      optional :bill_ref_number, :string, 6
      optional :org_account_balance, :int32, 7
      optional :third_party_trans_id, :string, 8
      optional :msisdn, :string, 9
      optional :first_name, :string, 10
      optional :middle_name, :string, 11
      optional :last_name, :string, 12
    end
    add_message "kash.services.CustomerToBusinessPaymentResultResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :success, :message, 2, "kash.services.CustomerToBusinessPaymentResultSuccessResponse"
        optional :error, :message, 3, "kash.services.CustomerToBusinessPaymentResultErrorResponse"
        optional :exception, :message, 4, "kash.services.CustomerToBusinessPaymentResultExceptionResponse"
      end
    end
    add_message "kash.services.BusinessToCustomerPaymentSuccessResponse" do
      optional :originator_conversation_id, :string, 1
      optional :conversation_id, :string, 2
      optional :response_description, :string, 3
    end
    add_message "kash.services.BusinessToCustomerPaymentErrorResponse" do
      optional :request_id, :string, 1
      optional :error_code, :string, 2
      optional :error_message, :string, 3
    end
    add_message "kash.services.BusinessToCustomerPaymentExceptionResponse" do
      optional :exception_code, :string, 1
      optional :exception_message, :string, 2
    end
    add_message "kash.services.BusinessToCustomerPaymentRequest" do
      optional :initiator_name, :string, 1
      optional :security_credential, :string, 2
      optional :command_id, :string, 3
      optional :amount, :int32, 4
      optional :party_a, :int32, 5
      optional :party_b, :int32, 6
      optional :remarks, :string, 7
      optional :queue_time_out_url, :string, 8
      optional :result_url, :string, 9
      optional :occasion, :string, 10
    end
    add_message "kash.services.BusinessToCustomerPaymentResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :success, :message, 2, "kash.services.BusinessToCustomerPaymentSuccessResponse"
        optional :error, :message, 3, "kash.services.BusinessToCustomerPaymentErrorResponse"
        optional :exception, :message, 4, "kash.services.BusinessToCustomerPaymentExceptionResponse"
      end
    end
    add_message "kash.services.BusinessToCustomerPaymentResultSuccessResponse" do
      optional :conversation_id, :string, 1
      optional :originator_conversation_id, :string, 2
      optional :result_desc, :string, 3
      optional :result_type, :int32, 4
      optional :result_code, :int32, 5
      optional :transaction_id, :string, 6
      optional :transaction_receipt, :string, 7
      optional :transaction_amount, :int32, 8
      optional :b2c_working_account_available_funds, :int32, 9
      optional :b2c_utility_account_available_funds, :int32, 10
      optional :transaction_completed_date_time, :string, 11
      optional :receiver_party_public_name, :string, 12
      optional :b2c_charges_paid_account_available_funds, :int32, 13
      optional :b2c_RecipientIsRegisteredCustomer, :string, 14
    end
    add_message "kash.services.BusinessToCustomerPaymentResultErrorResponse" do
      optional :request_id, :string, 1
      optional :error_code, :string, 2
      optional :error_message, :string, 3
    end
    add_message "kash.services.BusinessToCustomerPaymentResultExceptionResponse" do
      optional :exception_code, :string, 1
      optional :exception_message, :string, 2
    end
    add_message "kash.services.BusinessToCustomerPaymentResultRequest" do
      optional :conversation_id, :string, 1
      optional :originator_conversation_id, :string, 2
      optional :result_desc, :string, 3
      optional :result_type, :int32, 4
      optional :result_code, :int32, 5
      optional :transaction_id, :string, 6
      optional :transaction_receipt, :string, 7
      optional :transaction_amount, :int32, 8
      optional :b2c_working_account_available_funds, :int32, 9
      optional :b2c_utility_account_available_funds, :int32, 10
      optional :transaction_completed_date_time, :string, 11
      optional :receiver_party_public_name, :string, 12
      optional :b2c_charges_paid_account_available_funds, :int32, 13
      optional :b2c_RecipientIsRegisteredCustomer, :string, 14
    end
    add_message "kash.services.BusinessToCustomerPaymentResultResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :success, :message, 2, "kash.services.BusinessToCustomerPaymentResultSuccessResponse"
        optional :error, :message, 3, "kash.services.BusinessToCustomerPaymentResultErrorResponse"
        optional :exception, :message, 4, "kash.services.BusinessToCustomerPaymentResultExceptionResponse"
      end
    end
    add_message "kash.services.TransactionStatusSuccessResponse" do
      optional :originator_conversation_id, :string, 1
      optional :conversation_id, :string, 2
      optional :response_description, :string, 3
    end
    add_message "kash.services.TransactionStatusErrorResponse" do
      optional :request_id, :string, 1
      optional :error_code, :string, 2
      optional :error_message, :string, 3
    end
    add_message "kash.services.TransactionStatusExceptionResponse" do
      optional :exception_code, :string, 1
      optional :exception_message, :string, 2
    end
    add_message "kash.services.TransactionStatusRequest" do
      optional :command_id, :string, 1
      optional :party_a, :int32, 2
      optional :identifier_type, :int32, 3
      optional :remarks, :string, 4
      optional :initiator, :string, 5
      optional :security_credential, :string, 6
      optional :queue_time_out_url, :string, 7
      optional :result_url, :string, 8
      optional :transaction_id, :string, 9
      optional :occasion, :string, 10
    end
    add_message "kash.services.TransactionStatusResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :success, :message, 2, "kash.services.TransactionStatusSuccessResponse"
        optional :error, :message, 3, "kash.services.TransactionStatusErrorResponse"
        optional :exception, :message, 4, "kash.services.TransactionStatusExceptionResponse"
      end
    end
    add_message "kash.services.AccountBalanceSuccessResponse" do
      optional :originator_conversation_id, :string, 1
      optional :conversation_id, :string, 2
      optional :response_description, :string, 3
    end
    add_message "kash.services.AccountBalanceErrorResponse" do
      optional :request_id, :string, 1
      optional :error_code, :string, 2
      optional :error_message, :string, 3
    end
    add_message "kash.services.AccountBalanceExceptionResponse" do
      optional :exception_code, :string, 1
      optional :exception_message, :string, 2
    end
    add_message "kash.services.AccountBalanceRequest" do
      optional :command_id, :string, 1
      optional :party_a, :int32, 2
      optional :identifier_type, :int32, 3
      optional :remarks, :string, 4
      optional :initiator, :string, 5
      optional :security_credential, :string, 6
      optional :queue_time_out_url, :string, 7
      optional :result_url, :string, 8
    end
    add_message "kash.services.AccountBalanceResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :success, :message, 2, "kash.services.AccountBalanceSuccessResponse"
        optional :error, :message, 3, "kash.services.AccountBalanceErrorResponse"
        optional :exception, :message, 4, "kash.services.AccountBalanceExceptionResponse"
      end
    end
    add_message "kash.services.AccountBalanceCallbackSuccessResponse" do
      optional :result_type, :int32, 1
      optional :result_code, :int32, 2
      optional :result_desc, :string, 3
      optional :originator_converstion_id, :string, 4
      optional :conversation_id, :string, 5
      optional :transaction_id, :string, 6
      optional :parameters, :message, 7, "kash.services.Metadata"
    end
    add_message "kash.services.AccountBalanceCallbackErrorResponse" do
      optional :request_id, :string, 1
      optional :error_code, :string, 2
      optional :error_message, :string, 3
    end
    add_message "kash.services.AccountBalanceCallbackExceptionResponse" do
      optional :exception_code, :string, 1
      optional :exception_message, :string, 2
    end
    add_message "kash.services.AccountBalanceCallbackRequest" do
      optional :result_type, :int32, 1
      optional :result_code, :int32, 2
      optional :result_desc, :string, 3
      optional :originator_converstion_id, :string, 4
      optional :conversation_id, :string, 5
      optional :transaction_id, :string, 6
      optional :parameters, :message, 7, "kash.services.Metadata"
    end
    add_message "kash.services.AccountBalanceCallbackResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :success, :message, 2, "kash.services.AccountBalanceCallbackSuccessResponse"
        optional :error, :message, 3, "kash.services.AccountBalanceCallbackErrorResponse"
        optional :exception, :message, 4, "kash.services.AccountBalanceCallbackExceptionResponse"
      end
    end
    add_message "kash.services.ReversalSuccessResponse" do
      optional :originator_conversation_id, :string, 1
      optional :conversation_id, :string, 2
      optional :response_description, :string, 3
    end
    add_message "kash.services.ReversalErrorResponse" do
      optional :request_id, :string, 1
      optional :error_code, :string, 2
      optional :error_message, :string, 3
    end
    add_message "kash.services.ReversalExceptionResponse" do
      optional :exception_code, :string, 1
      optional :exception_message, :string, 2
    end
    add_message "kash.services.ReversalRequest" do
      optional :command_id, :string, 1
      optional :receiver_party, :int32, 2
      optional :receiver_identifier_type, :int32, 3
      optional :remarks, :string, 4
      optional :initiator, :string, 5
      optional :security_credential, :string, 6
      optional :queue_time_out_url, :string, 7
      optional :result_url, :string, 8
      optional :transaction_id, :string, 9
      optional :occasion, :string, 10
    end
    add_message "kash.services.ReversalResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :success, :message, 2, "kash.services.ReversalSuccessResponse"
        optional :error, :message, 3, "kash.services.ReversalErrorResponse"
        optional :exception, :message, 4, "kash.services.ReversalExceptionResponse"
      end
    end
  end
end

module Kash
  module Services
    AuthorizationSuccessResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.AuthorizationSuccessResponse").msgclass
    AuthorizationErrorResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.AuthorizationErrorResponse").msgclass
    AuthorizationExceptionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.AuthorizationExceptionResponse").msgclass
    AuthorizationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.AuthorizationRequest").msgclass
    AuthorizationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.AuthorizationResponse").msgclass
    DynamicQRCodeSuccessResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.DynamicQRCodeSuccessResponse").msgclass
    DynamicQRCodeErrorResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.DynamicQRCodeErrorResponse").msgclass
    DynamicQRCodeExceptionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.DynamicQRCodeExceptionResponse").msgclass
    DynamicQRCodeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.DynamicQRCodeRequest").msgclass
    DynamicQRCodeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.DynamicQRCodeResponse").msgclass
    StkPushSuccessResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.StkPushSuccessResponse").msgclass
    StkPushErrorResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.StkPushErrorResponse").msgclass
    StkPushExceptionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.StkPushExceptionResponse").msgclass
    StkPushRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.StkPushRequest").msgclass
    StkPushResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.StkPushResponse").msgclass
    Callback = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.Callback").msgclass
    Dataset = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.Dataset").msgclass
    Metadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.Metadata").msgclass
    StkPushCallbackSuccessResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.StkPushCallbackSuccessResponse").msgclass
    StkPushCallbackErrorResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.StkPushCallbackErrorResponse").msgclass
    StkPushCallbackExceptionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.StkPushCallbackExceptionResponse").msgclass
    StkPushCallbackRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.StkPushCallbackRequest").msgclass
    StkPushCallbackResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.StkPushCallbackResponse").msgclass
    StkPushQuerySuccessResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.StkPushQuerySuccessResponse").msgclass
    StkPushQueryErrorResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.StkPushQueryErrorResponse").msgclass
    StkPushQueryExceptionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.StkPushQueryExceptionResponse").msgclass
    StkPushQueryRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.StkPushQueryRequest").msgclass
    StkPushQueryResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.StkPushQueryResponse").msgclass
    CustomerToBusinessRegisterUrlSuccessResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.CustomerToBusinessRegisterUrlSuccessResponse").msgclass
    CustomerToBusinessRegisterUrlErrorResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.CustomerToBusinessRegisterUrlErrorResponse").msgclass
    CustomerToBusinessRegisterUrlExceptionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.CustomerToBusinessRegisterUrlExceptionResponse").msgclass
    CustomerToBusinessRegisterUrlRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.CustomerToBusinessRegisterUrlRequest").msgclass
    CustomerToBusinessRegisterUrlResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.CustomerToBusinessRegisterUrlResponse").msgclass
    CustomerToBusinessPaymentSuccessResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.CustomerToBusinessPaymentSuccessResponse").msgclass
    CustomerToBusinessPaymentErrorResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.CustomerToBusinessPaymentErrorResponse").msgclass
    CustomerToBusinessPaymentExceptionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.CustomerToBusinessPaymentExceptionResponse").msgclass
    CustomerToBusinessPaymentRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.CustomerToBusinessPaymentRequest").msgclass
    CustomerToBusinessPaymentResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.CustomerToBusinessPaymentResponse").msgclass
    CustomerToBusinessPaymentResultSuccessResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.CustomerToBusinessPaymentResultSuccessResponse").msgclass
    CustomerToBusinessPaymentResultErrorResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.CustomerToBusinessPaymentResultErrorResponse").msgclass
    CustomerToBusinessPaymentResultExceptionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.CustomerToBusinessPaymentResultExceptionResponse").msgclass
    CustomerToBusinessPaymentResultRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.CustomerToBusinessPaymentResultRequest").msgclass
    CustomerToBusinessPaymentResultResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.CustomerToBusinessPaymentResultResponse").msgclass
    BusinessToCustomerPaymentSuccessResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.BusinessToCustomerPaymentSuccessResponse").msgclass
    BusinessToCustomerPaymentErrorResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.BusinessToCustomerPaymentErrorResponse").msgclass
    BusinessToCustomerPaymentExceptionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.BusinessToCustomerPaymentExceptionResponse").msgclass
    BusinessToCustomerPaymentRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.BusinessToCustomerPaymentRequest").msgclass
    BusinessToCustomerPaymentResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.BusinessToCustomerPaymentResponse").msgclass
    BusinessToCustomerPaymentResultSuccessResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.BusinessToCustomerPaymentResultSuccessResponse").msgclass
    BusinessToCustomerPaymentResultErrorResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.BusinessToCustomerPaymentResultErrorResponse").msgclass
    BusinessToCustomerPaymentResultExceptionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.BusinessToCustomerPaymentResultExceptionResponse").msgclass
    BusinessToCustomerPaymentResultRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.BusinessToCustomerPaymentResultRequest").msgclass
    BusinessToCustomerPaymentResultResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.BusinessToCustomerPaymentResultResponse").msgclass
    TransactionStatusSuccessResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.TransactionStatusSuccessResponse").msgclass
    TransactionStatusErrorResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.TransactionStatusErrorResponse").msgclass
    TransactionStatusExceptionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.TransactionStatusExceptionResponse").msgclass
    TransactionStatusRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.TransactionStatusRequest").msgclass
    TransactionStatusResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.TransactionStatusResponse").msgclass
    AccountBalanceSuccessResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.AccountBalanceSuccessResponse").msgclass
    AccountBalanceErrorResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.AccountBalanceErrorResponse").msgclass
    AccountBalanceExceptionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.AccountBalanceExceptionResponse").msgclass
    AccountBalanceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.AccountBalanceRequest").msgclass
    AccountBalanceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.AccountBalanceResponse").msgclass
    AccountBalanceCallbackSuccessResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.AccountBalanceCallbackSuccessResponse").msgclass
    AccountBalanceCallbackErrorResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.AccountBalanceCallbackErrorResponse").msgclass
    AccountBalanceCallbackExceptionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.AccountBalanceCallbackExceptionResponse").msgclass
    AccountBalanceCallbackRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.AccountBalanceCallbackRequest").msgclass
    AccountBalanceCallbackResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.AccountBalanceCallbackResponse").msgclass
    ReversalSuccessResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.ReversalSuccessResponse").msgclass
    ReversalErrorResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.ReversalErrorResponse").msgclass
    ReversalExceptionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.ReversalExceptionResponse").msgclass
    ReversalRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.ReversalRequest").msgclass
    ReversalResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("kash.services.ReversalResponse").msgclass
  end
end
